//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.19 at 08:00:00 PM ALMT 
//


package ru.geekbrains.march.market.soap.products;

import ru.geekbrains.march.market.dtos.ProductDto;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productDto" type="{http://www.geekbrains.ru/march/market/products}productDto"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productDto"
})
@XmlRootElement(name = "getProductByIdResponse")
public class GetProductByIdResponse {

    @XmlElement(required = true)
    protected ProductDto productDto;

    /**
     * Gets the value of the productDto property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDto }
     *     
     */
    public ProductDto getProductDto() {
        return productDto;
    }

    /**
     * Sets the value of the productDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDto }
     *     
     */
    public void setProductDto(ProductDto value) {
        this.productDto = value;
    }

}
